<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"><head><title>TestNG Report</title><style type="text/css">table {margin-bottom:10px;border-collapse:collapse;empty-cells:show}th,td {border:1px solid #009;padding:.25em .5em}th {vertical-align:bottom}td {vertical-align:top}table a {font-weight:bold}.stripe td {background-color: #E6EBF9}.num {text-align:right}.passedodd td {background-color: #3F3}.passedeven td {background-color: #0A0}.skippedodd td {background-color: #DDD}.skippedeven td {background-color: #CCC}.failedodd td,.attn {background-color: #F33}.failedeven td,.stripe .attn {background-color: #D00}.stacktrace {white-space:pre;font-family:monospace}.totop {font-size:85%;text-align:center;border-bottom:2px solid #000}</style></head><body><table><tr><th>Test</th><th># Passed</th><th># Skipped</th><th># Failed</th><th>Time (ms)</th><th>Included Groups</th><th>Excluded Groups</th></tr><tr><th colspan="7">Suite</th></tr><tr><th colspan="7">P2P/XD/XT_CooperationModel</th></tr><tr><td><a href="#t0">P2P_DR模式下购买手机系列A产品的测试场景点</a></td><td class="num">19</td><td class="num">0</td><td class="num attn">2</td><td class="num">682,517</td><td></td><td></td></tr><tr class="stripe"><td><a href="#t1">P2P_PPM模式下购买手机系列A产品的测试场景点</a></td><td class="num">1</td><td class="num">0</td><td class="num attn">23</td><td class="num">661,115</td><td></td><td></td></tr><tr><th>Total</th><th class="num">20</th><th class="num">0</th><th class="num attn">25</th><th class="num">1,343,632</th><th colspan="2"></th></tr></table><table><thead><tr><th>Class</th><th>Method</th><th>Start</th><th>Time (ms)</th></tr></thead><tbody><tr><th colspan="4">Suite</th></tr></tbody><tbody><tr><th colspan="4">P2P/XD/XT_CooperationModel</th></tr></tbody><tbody id="t0"><tr><th colspan="4">P2P_DR模式下购买手机系列A产品的测试场景点 &#8212; failed</th></tr><tr class="failedeven"><td rowspan="2">TestCases.P2P_DR_Mobile_SeriesA</td><td><a href="#m0">case1</a></td><td rowspan="1">1506766073232</td><td rowspan="1">3658</td></tr><tr class="failedeven"><td><a href="#m1">case_18</a></td><td rowspan="1">1506766677694</td><td rowspan="1">6823</td></tr><tr><th colspan="4">P2P_DR模式下购买手机系列A产品的测试场景点 &#8212; passed</th></tr><tr class="passedeven"><td rowspan="19">TestCases.P2P_DR_Mobile_SeriesA</td><td><a href="#m2">Precondition</a></td><td rowspan="1">1506766072622</td><td rowspan="1">610</td></tr><tr class="passedeven"><td><a href="#m3">case2</a></td><td rowspan="1">1506766076890</td><td rowspan="1">1744</td></tr><tr class="passedeven"><td><a href="#m4">case3</a></td><td rowspan="1">1506766078634</td><td rowspan="1">21744</td></tr><tr class="passedeven"><td><a href="#m5">case4</a></td><td rowspan="1">1506766100378</td><td rowspan="1">38177</td></tr><tr class="passedeven"><td><a href="#m6">case5</a></td><td rowspan="1">1506766138555</td><td rowspan="1">4528</td></tr><tr class="passedeven"><td><a href="#m7">case6</a></td><td rowspan="1">1506766143083</td><td rowspan="1">22210</td></tr><tr class="passedeven"><td><a href="#m8">case7</a></td><td rowspan="1">1506766165293</td><td rowspan="1">77084</td></tr><tr class="passedeven"><td><a href="#m9">case8</a></td><td rowspan="1">1506766242377</td><td rowspan="1">199631</td></tr><tr class="passedeven"><td><a href="#m10">case9</a></td><td rowspan="1">1506766442008</td><td rowspan="1">111841</td></tr><tr class="passedeven"><td><a href="#m11">case_10</a></td><td rowspan="1">1506766553849</td><td rowspan="1">41502</td></tr><tr class="passedeven"><td><a href="#m12">case_11</a></td><td rowspan="1">1506766595351</td><td rowspan="1">20384</td></tr><tr class="passedeven"><td><a href="#m13">case_12</a></td><td rowspan="1">1506766615735</td><td rowspan="1">12397</td></tr><tr class="passedeven"><td><a href="#m14">case_13</a></td><td rowspan="1">1506766628132</td><td rowspan="1">2001</td></tr><tr class="passedeven"><td><a href="#m15">case_14</a></td><td rowspan="1">1506766630133</td><td rowspan="1">2112</td></tr><tr class="passedeven"><td><a href="#m16">case_15</a></td><td rowspan="1">1506766632245</td><td rowspan="1">32330</td></tr><tr class="passedeven"><td><a href="#m17">case_16</a></td><td rowspan="1">1506766664575</td><td rowspan="1">10616</td></tr><tr class="passedeven"><td><a href="#m18">case_17</a></td><td rowspan="1">1506766675191</td><td rowspan="1">2502</td></tr><tr class="passedeven"><td><a href="#m19">case_19</a></td><td rowspan="1">1506766684517</td><td rowspan="1">2150</td></tr><tr class="passedeven"><td><a href="#m20">case_20</a></td><td rowspan="1">1506766686667</td><td rowspan="1">22797</td></tr></tbody><tbody id="t1"><tr><th colspan="4">P2P_PPM模式下购买手机系列A产品的测试场景点 &#8212; failed</th></tr><tr class="failedeven"><td rowspan="23">TestCases.P2P_PPM_Mobile_SeriesA</td><td><a href="#m21">case1</a></td><td rowspan="1">1506766742025</td><td rowspan="1">10063</td></tr><tr class="failedeven"><td><a href="#m22">case2</a></td><td rowspan="1">1506766752088</td><td rowspan="1">30583</td></tr><tr class="failedeven"><td><a href="#m23">case3</a></td><td rowspan="1">1506766782672</td><td rowspan="1">30243</td></tr><tr class="failedeven"><td><a href="#m24">case4</a></td><td rowspan="1">1506766812915</td><td rowspan="1">30398</td></tr><tr class="failedeven"><td><a href="#m25">case5</a></td><td rowspan="1">1506766843314</td><td rowspan="1">30581</td></tr><tr class="failedeven"><td><a href="#m26">case6</a></td><td rowspan="1">1506766873895</td><td rowspan="1">30434</td></tr><tr class="failedeven"><td><a href="#m27">case7</a></td><td rowspan="1">1506766904329</td><td rowspan="1">10544</td></tr><tr class="failedeven"><td><a href="#m28">case8</a></td><td rowspan="1">1506766914874</td><td rowspan="1">30551</td></tr><tr class="failedeven"><td><a href="#m29">case9</a></td><td rowspan="1">1506766945425</td><td rowspan="1">30052</td></tr><tr class="failedeven"><td><a href="#m30">case_10</a></td><td rowspan="1">1506766975477</td><td rowspan="1">30346</td></tr><tr class="failedeven"><td><a href="#m31">case_11</a></td><td rowspan="1">1506767005823</td><td rowspan="1">30411</td></tr><tr class="failedeven"><td><a href="#m32">case_12</a></td><td rowspan="1">1506767036234</td><td rowspan="1">30279</td></tr><tr class="failedeven"><td><a href="#m33">case_13</a></td><td rowspan="1">1506767066513</td><td rowspan="1">10539</td></tr><tr class="failedeven"><td><a href="#m34">case_14</a></td><td rowspan="1">1506767077052</td><td rowspan="1">30325</td></tr><tr class="failedeven"><td><a href="#m35">case_15</a></td><td rowspan="1">1506767107378</td><td rowspan="1">10129</td></tr><tr class="failedeven"><td><a href="#m36">case_16</a></td><td rowspan="1">1506767117508</td><td rowspan="1">30360</td></tr><tr class="failedeven"><td><a href="#m37">case_17</a></td><td rowspan="1">1506767147868</td><td rowspan="1">10289</td></tr><tr class="failedeven"><td><a href="#m38">case_18</a></td><td rowspan="1">1506767158157</td><td rowspan="1">30078</td></tr><tr class="failedeven"><td><a href="#m39">case_19</a></td><td rowspan="1">1506767188235</td><td rowspan="1">30048</td></tr><tr class="failedeven"><td><a href="#m40">case_20</a></td><td rowspan="1">1506767218284</td><td rowspan="1">91221</td></tr><tr class="failedeven"><td><a href="#m41">case_21</a></td><td rowspan="1">1506767309506</td><td rowspan="1">31977</td></tr><tr class="failedeven"><td><a href="#m42">case_22</a></td><td rowspan="1">1506767341484</td><td rowspan="1">29199</td></tr><tr class="failedeven"><td><a href="#m43">case_23</a></td><td rowspan="1">1506767370683</td><td rowspan="1">1021</td></tr><tr><th colspan="4">P2P_PPM模式下购买手机系列A产品的测试场景点 &#8212; passed</th></tr><tr class="passedeven"><td rowspan="1">TestCases.P2P_PPM_Mobile_SeriesA</td><td><a href="#m44">Precondition</a></td><td rowspan="1">1506766741498</td><td rowspan="1">527</td></tr></tbody></table><h2>P2P_DR模式下购买手机系列A产品的测试场景点</h2><h3 id="m0">TestCases.P2P_DR_Mobile_SeriesA#case1</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_DR_Mobile_SeriesA.case1(P2P_DR_Mobile_SeriesA.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: 安装启动失败(实际结果和预期结果不一致)  Actual 【开始体验】  but found 【开始体验1】
	at org.testng.Assert.fail(Assert.java:94)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.checkEquals(CheckAction_Handler.java:103)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:40)
	... 18 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m1">TestCases.P2P_DR_Mobile_SeriesA#case_18</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor23.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_DR_Mobile_SeriesA.case_18(P2P_DR_Mobile_SeriesA.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.AssertionError: 未发现审核通过的合同或合同状态未改变(实际结果和预期结果不一致)  Actual 【时雪多】  but found 【时雪】
	at org.testng.Assert.fail(Assert.java:94)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.checkEquals(CheckAction_Handler.java:103)
	at com.dafycredit.giveu.test.handler.CheckAction_Handler.check(CheckAction_Handler.java:40)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m2">TestCases.P2P_DR_Mobile_SeriesA#Precondition</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在数据库中,执行对应SQL语句,可以正常执行成功</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m3">TestCases.P2P_DR_Mobile_SeriesA#case2</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在引导页最后一页界面,点击开始体验按钮后,可以正常进入登录界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m4">TestCases.P2P_DR_Mobile_SeriesA#case3</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在登录界面,输入正确的账号和密码,已连接网络和开启GPS定位权限时,点击登录按钮后,可以正常登录并进入设置解锁密码界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m5">TestCases.P2P_DR_Mobile_SeriesA#case4</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在新建订单界面,选择输入对应产品信息,点击下一步按钮后,可以正常进入产品列表界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m6">TestCases.P2P_DR_Mobile_SeriesA#case5</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在产品列表界面,选择对应产品信息,点击下一步按钮后,可以正常进入商品信息界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m7">TestCases.P2P_DR_Mobile_SeriesA#case6</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在商品信息界面,选择输入对应商品信息,点击下一步按钮后,可以正常进入客户信息界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m8">TestCases.P2P_DR_Mobile_SeriesA#case7</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在客户信息界面,上传输入对应客户身份证正反面照片信息,点击生成订单按钮后,可以正常进入基本信息界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m9">TestCases.P2P_DR_Mobile_SeriesA#case8</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在基本信息界面,选择输入对应客户基本信息,点击下一步按钮后,可以正常进入单位信息界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m10">TestCases.P2P_DR_Mobile_SeriesA#case9</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在单位信息界面,选择输入对应客户单位信息,点击下一步按钮后,可以正常进入联系人填写界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m11">TestCases.P2P_DR_Mobile_SeriesA#case_10</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在联系人填写界面,选择输入对应客户联系人信息,点击下一步按钮后,可以正常进入绑定银行卡界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m12">TestCases.P2P_DR_Mobile_SeriesA#case_11</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在绑定银行卡界面,输入对应客户银行卡信息,点击下一步按钮后,可以正常进入其他信息界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m13">TestCases.P2P_DR_Mobile_SeriesA#case_12</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在其他信息界面,输入对应客户其他信息,点击下一步按钮后,可以正常进入芝麻信用认证界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m14">TestCases.P2P_DR_Mobile_SeriesA#case_13</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在芝麻信用认证界面,点击跳过认证按钮后,可以正常跳过认证并进入运营商授权认证界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m15">TestCases.P2P_DR_Mobile_SeriesA#case_14</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在运营商授权认证界面,点击跳过认证按钮后,可以正常跳过认证并进入影像证明界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m16">TestCases.P2P_DR_Mobile_SeriesA#case_15</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在影像证明界面,上传对应客户影像证明照片,点击确认提交按钮后,可以正常弹出请输入登录密码,以验证身份界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m17">TestCases.P2P_DR_Mobile_SeriesA#case_16</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在请输入登录密码,以验证身份界面,输入对应用户登录密码,点击确认按钮后,可以正常提交合同并进入成功提交界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m18">TestCases.P2P_DR_Mobile_SeriesA#case_17</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在成功提交界面,点击查看订单按钮后,可以正常进入订单列表-审核中列界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m19">TestCases.P2P_DR_Mobile_SeriesA#case_19</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在审核通过列界面,选择对应合同点击补传资料按钮后,可以正常进入补传资料界面</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m20">TestCases.P2P_DR_Mobile_SeriesA#case_20</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在补传资料界面,输入上传对应手机串号和IMEI码照片,点击确认提交按钮后,可以正常提交成功并返回审核通过列界面,且出现确认注册按钮</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h2>P2P_PPM模式下购买手机系列A产品的测试场景点</h2><h3 id="m21">TestCases.P2P_PPM_Mobile_SeriesA#case1</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case1(P2P_PPM_Mobile_SeriesA.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m22">TestCases.P2P_PPM_Mobile_SeriesA#case2</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case2(P2P_PPM_Mobile_SeriesA.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m23">TestCases.P2P_PPM_Mobile_SeriesA#case3</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case3(P2P_PPM_Mobile_SeriesA.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m24">TestCases.P2P_PPM_Mobile_SeriesA#case4</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case4(P2P_PPM_Mobile_SeriesA.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m25">TestCases.P2P_PPM_Mobile_SeriesA#case5</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case5(P2P_PPM_Mobile_SeriesA.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m26">TestCases.P2P_PPM_Mobile_SeriesA#case6</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case6(P2P_PPM_Mobile_SeriesA.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m27">TestCases.P2P_PPM_Mobile_SeriesA#case7</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case7(P2P_PPM_Mobile_SeriesA.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m28">TestCases.P2P_PPM_Mobile_SeriesA#case8</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case8(P2P_PPM_Mobile_SeriesA.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m29">TestCases.P2P_PPM_Mobile_SeriesA#case9</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case9(P2P_PPM_Mobile_SeriesA.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m30">TestCases.P2P_PPM_Mobile_SeriesA#case_10</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_10(P2P_PPM_Mobile_SeriesA.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m31">TestCases.P2P_PPM_Mobile_SeriesA#case_11</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_11(P2P_PPM_Mobile_SeriesA.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m32">TestCases.P2P_PPM_Mobile_SeriesA#case_12</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_12(P2P_PPM_Mobile_SeriesA.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m33">TestCases.P2P_PPM_Mobile_SeriesA#case_13</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_13(P2P_PPM_Mobile_SeriesA.java:102)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m34">TestCases.P2P_PPM_Mobile_SeriesA#case_14</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_14(P2P_PPM_Mobile_SeriesA.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m35">TestCases.P2P_PPM_Mobile_SeriesA#case_15</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$2.run(Step_Action.java:41)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_15(P2P_PPM_Mobile_SeriesA.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m36">TestCases.P2P_PPM_Mobile_SeriesA#case_16</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_16(P2P_PPM_Mobile_SeriesA.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m37">TestCases.P2P_PPM_Mobile_SeriesA#case_17</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.base.Step_Action$3.run(Step_Action.java:52)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:101)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_17(P2P_PPM_Mobile_SeriesA.java:126)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m38">TestCases.P2P_PPM_Mobile_SeriesA#case_18</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_18(P2P_PPM_Mobile_SeriesA.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m39">TestCases.P2P_PPM_Mobile_SeriesA#case_19</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_19(P2P_PPM_Mobile_SeriesA.java:138)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m40">TestCases.P2P_PPM_Mobile_SeriesA#case_20</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_20(P2P_PPM_Mobile_SeriesA.java:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m41">TestCases.P2P_PPM_Mobile_SeriesA#case_21</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_21(P2P_PPM_Mobile_SeriesA.java:150)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:90)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m42">TestCases.P2P_PPM_Mobile_SeriesA#case_22</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor22.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_22(P2P_PPM_Mobile_SeriesA.java:156)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: &apos;2.53.0&apos;, revision: &apos;35ae25b1534ae328c771e0856c93e187490ca824&apos;, time: &apos;2016-03-15 10:43:46&apos;
System info: host: &apos;King&apos;, ip: &apos;192.168.98.2&apos;, os.name: &apos;Windows 8.1&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.3&apos;, java.version: &apos;1.8.0_91&apos;
Driver info: driver.version: AndroidDriver
Capabilities [{appPackage=com.giveu.corder, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=b62f7ec6, fullReset=false, platform=LINUX, appActivity=.index.activity.SplashActivity, desired={appPackage=com.giveu.corder, noReset=true, deviceName=Android Emulator, fullReset=false, appActivity=.index.activity.SplashActivity, newCommandTimeout=60000, platformVersion=4.2.2, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}, newCommandTimeout=60000, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}]
Session ID: 4afa3647-b9d3-4434-a52e-265fd71e5b6b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:388)
	at io.appium.java_client.android.AndroidDriver.findElementsByAndroidUIAutomator(AndroidDriver.java:403)
	at com.dafycredit.giveu.test.util.Appium_Util.getElement(Appium_Util.java:77)
	at com.dafycredit.giveu.test.handler.ClickAction_Handler.click(ClickAction_Handler.java:30)
	... 17 more
Caused by: org.openqa.selenium.WebDriverException: java.net.SocketException: Connection reset
Build info: version: &apos;2.53.0&apos;, revision: &apos;35ae25b1534ae328c771e0856c93e187490ca824&apos;, time: &apos;2016-03-15 10:43:46&apos;
System info: host: &apos;King&apos;, ip: &apos;192.168.98.2&apos;, os.name: &apos;Windows 8.1&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.3&apos;, java.version: &apos;1.8.0_91&apos;
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 24 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:87)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
	at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.http.impl.conn.CPoolProxy.invoke(CPoolProxy.java:138)
	at com.sun.proxy.$Proxy5.receiveResponseHeader(Unknown Source)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:67)
	... 25 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m43">TestCases.P2P_PPM_Mobile_SeriesA#case_23</h3><table class="result"><tr><th>Exception</th></tr><tr><td><div class="stacktrace">java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.dafycredit.giveu.test.service.RunUnit_Service.runCase(RunUnit_Service.java:99)
	at TestCases.P2P_PPM_Mobile_SeriesA.case_23(P2P_PPM_Mobile_SeriesA.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: &apos;2.53.0&apos;, revision: &apos;35ae25b1534ae328c771e0856c93e187490ca824&apos;, time: &apos;2016-03-15 10:43:46&apos;
System info: host: &apos;King&apos;, ip: &apos;192.168.98.2&apos;, os.name: &apos;Windows 8.1&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.3&apos;, java.version: &apos;1.8.0_91&apos;
Driver info: driver.version: AndroidDriver
Capabilities [{appPackage=com.giveu.corder, networkConnectionEnabled=true, noReset=true, warnings={}, databaseEnabled=false, deviceName=b62f7ec6, fullReset=false, platform=LINUX, appActivity=.index.activity.SplashActivity, desired={appPackage=com.giveu.corder, noReset=true, deviceName=Android Emulator, fullReset=false, appActivity=.index.activity.SplashActivity, newCommandTimeout=60000, platformVersion=4.2.2, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}, newCommandTimeout=60000, platformVersion=6.0.1, webStorageEnabled=false, locationContextEnabled=false, browserName=Android, takesScreenshot=true, javascriptEnabled=true, sessionOverride=true, unicodeKeyboard=true, autoWebview=true, platformName=Android, device=uiautomator, resetKeyboard=true}]
Session ID: 4afa3647-b9d3-4434-a52e-265fd71e5b6b
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:665)
	at io.appium.java_client.DefaultGenericMobileDriver.execute(DefaultGenericMobileDriver.java:42)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.execute(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver$RemoteWebDriverOptions$RemoteTimeouts.implicitlyWait(RemoteWebDriver.java:865)
	at com.dafycredit.giveu.test.handler.DBAction_Handler.dbQuery(DBAction_Handler.java:54)
	... 18 more
Caused by: org.openqa.selenium.WebDriverException: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
Build info: version: &apos;2.53.0&apos;, revision: &apos;35ae25b1534ae328c771e0856c93e187490ca824&apos;, time: &apos;2016-03-15 10:43:46&apos;
System info: host: &apos;King&apos;, ip: &apos;192.168.98.2&apos;, os.name: &apos;Windows 8.1&apos;, os.arch: &apos;amd64&apos;, os.version: &apos;6.3&apos;, java.version: &apos;1.8.0_91&apos;
Driver info: driver.version: AndroidDriver
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:79)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:644)
	... 23 more
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused: connect
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:144)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:90)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:142)
	at io.appium.java_client.remote.AppiumCommandExecutor.execute(AppiumCommandExecutor.java:67)
	... 24 more
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 37 more
</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p><h3 id="m44">TestCases.P2P_PPM_Mobile_SeriesA#Precondition</h3><table class="result"><tr><th>Messages</th></tr><tr><td><div class="messages">验证在数据库中,执行对应SQL语句,可以正常执行成功</div></td></tr></table><p class="totop"><a href="#summary">back to summary</a></p></body></html>